<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {



        Schema::disableForeignKeyConstraints();
        DB::table('nationalities')->truncate();
        Schema::enableForeignKeyConstraints();
        $nationalities = [
            ['name' => 'Afghanistan ', 'flag' => 'af ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Albania ', 'flag' => 'al ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Algeria ', 'flag' => 'dz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'American Samoa ', 'flag' => 'as ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Andorra ', 'flag' => 'ad ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Angola ', 'flag' => 'ao ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Anguilla ', 'flag' => 'ai ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Antarctica ', 'flag' => 'aq ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Antigua and Barbuda ', 'flag' => 'ag ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Argentina ', 'flag' => 'ar ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Armenia ', 'flag' => 'am ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Aruba ', 'flag' => 'aw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Australia ', 'flag' => 'au ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Austria ', 'flag' => 'at ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Azerbaijan ', 'flag' => 'az ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bahamas ', 'flag' => 'bs ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bahrain ', 'flag' => 'bh ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bangladesh ', 'flag' => 'bd ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barbados ', 'flag' => 'bb ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Belarus ', 'flag' => 'by ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Belgium ', 'flag' => 'be ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Belize ', 'flag' => 'bz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Benin ', 'flag' => 'bj ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bermuda ', 'flag' => 'bm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bhutan ', 'flag' => 'bt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bolivia', 'flag' => 'bo ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bonaire, Sint Eustatius and Saba ', 'flag' => 'bq ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bosnia and Herzegovina ', 'flag' => 'ba ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Botswana ', 'flag' => 'bw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bouvet Island ', 'flag' => 'bv ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Brazil ', 'flag' => 'br ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'British Indian Ocean Territory ', 'flag' => 'io ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Brunei Darussalam ', 'flag' => 'bn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bulgaria ', 'flag' => 'bg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Burkina Faso ', 'flag' => 'bf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Burundi ', 'flag' => 'bi ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cabo Verde ', 'flag' => 'cv ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cambodia ', 'flag' => 'kh ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cameroon ', 'flag' => 'cm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Canada ', 'flag' => 'ca ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cayman Islands', 'flag' => 'ky ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Central African Republic', 'flag' => 'cf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chad ', 'flag' => 'td ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chile ', 'flag' => 'cl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'China ', 'flag' => 'cn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Christmas Island ', 'flag' => 'cx ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Colombia ', 'flag' => 'co ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Comoros', 'flag' => 'km ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Congo', 'flag' => 'cd ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Congo ', 'flag' => 'cg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cook Islands ', 'flag' => 'ck ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Costa Rica ', 'flag' => 'cr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Croatia ', 'flag' => 'hr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cuba ', 'flag' => 'cu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Curaçao ', 'flag' => 'cw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cyprus ', 'flag' => 'cy ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Czechia ', 'flag' => 'cz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Côte d\'Ivoire ', 'flag' => 'ci ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Denmark ', 'flag' => 'dk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Djibouti ', 'flag' => 'dj ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Dominica ', 'flag' => 'dm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Dominican Republic ', 'flag' => 'do ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ecuador ', 'flag' => 'ec ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Egypt ', 'flag' => 'eg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Salvador ', 'flag' => 'sv ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Equatorial Guinea ', 'flag' => 'gq ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Eritrea ', 'flag' => 'er ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Estonia ', 'flag' => 'ee ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Eswatini ', 'flag' => 'sz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ethiopia ', 'flag' => 'et ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Falkland Islands [Malvinas] ', 'flag' => 'fk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Faroe Islands ', 'flag' => 'fo ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Fiji ', 'flag' => 'fj ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Finland ', 'flag' => 'fi ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'France ', 'flag' => 'fr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'French Guiana ', 'flag' => 'gf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'French Polynesia ', 'flag' => 'pf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'French Southern Territories ', 'flag' => 'tf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gabon ', 'flag' => 'ga ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gambia ', 'flag' => 'gm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Georgia ', 'flag' => 'ge ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Germany ', 'flag' => 'de ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ghana ', 'flag' => 'gh ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gibraltar ', 'flag' => 'gi ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Greece ', 'flag' => 'gr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Greenland ', 'flag' => 'gl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Grenada ', 'flag' => 'gd ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guadeloupe ', 'flag' => 'gp ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guam ', 'flag' => 'gu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guatemala ', 'flag' => 'gt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guernsey ', 'flag' => 'gg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guinea ', 'flag' => 'gn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guinea-Bissau ', 'flag' => 'gw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guyana ', 'flag' => 'gy ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Haiti ', 'flag' => 'ht ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Heard Island and McDonald Islands ', 'flag' => 'hm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Holy See ', 'flag' => 'va ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Honduras ', 'flag' => 'hn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Hong Kong ', 'flag' => 'hk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Hungary ', 'flag' => 'hu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Iceland ', 'flag' => 'is ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'India ', 'flag' => 'in ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Indonesia ', 'flag' => 'id ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Iran', 'flag' => 'ir ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Iraq ', 'flag' => 'iq ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ireland ', 'flag' => 'ie ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Isle of Man ', 'flag' => 'im ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Israel ', 'flag' => 'il ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Italy ', 'flag' => 'it ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Jamaica ', 'flag' => 'jm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Japan ', 'flag' => 'jp ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Jersey ', 'flag' => 'je ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Jordan ', 'flag' => 'jo ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Kazakhstan ', 'flag' => 'kz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Kenya ', 'flag' => 'ke ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Kiribati ', 'flag' => 'ki ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Korea (the Democratic People\'s Republic of) ', 'flag' => 'kp ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Korea (the Republic of) ', 'flag' => 'kr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Kuwait ', 'flag' => 'kw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Kyrgyzstan ', 'flag' => 'kg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lao People\'s Democratic Republic ', 'flag' => 'la ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Latvia ', 'flag' => 'lv ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lebanon ', 'flag' => 'lb ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lesotho ', 'flag' => 'ls ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Liberia ', 'flag' => 'lr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Libya ', 'flag' => 'ly ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Liechtenstein ', 'flag' => 'li ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lithuania ', 'flag' => 'lt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Luxembourg ', 'flag' => 'lu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Macao ', 'flag' => 'mo ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Madagascar ', 'flag' => 'mg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Malawi ', 'flag' => 'mw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Malaysia ', 'flag' => 'my ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Maldives ', 'flag' => 'mv ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mali ', 'flag' => 'ml ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Malta ', 'flag' => 'mt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Marshall Islands ', 'flag' => 'mh ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Martinique ', 'flag' => 'mq ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mauritania ', 'flag' => 'mr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mauritius ', 'flag' => 'mu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mayotte ', 'flag' => 'yt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mexico ', 'flag' => 'mx ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Micronesia (Federated States of) ', 'flag' => 'fm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Moldova (the Republic of) ', 'flag' => 'md ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Monaco ', 'flag' => 'mc ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mongolia ', 'flag' => 'mn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Montenegro ', 'flag' => 'me ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Montserrat ', 'flag' => 'ms ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Morocco ', 'flag' => 'ma ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mozambique ', 'flag' => 'mz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Myanmar ', 'flag' => 'mm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Namibia ', 'flag' => 'na ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nauru ', 'flag' => 'nr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nepal ', 'flag' => 'np ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Netherlands ', 'flag' => 'nl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'New Caledonia ', 'flag' => 'nc ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'New Zealand ', 'flag' => 'nz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nicaragua ', 'flag' => 'ni ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Niger ', 'flag' => 'ne ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nigeria ', 'flag' => 'ng ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Niue ', 'flag' => 'nu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Norfolk Island ', 'flag' => 'nf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Northern Mariana Islands ', 'flag' => 'mp ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Norway ', 'flag' => 'no ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Oman ', 'flag' => 'om ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pakistan ', 'flag' => 'pk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palau ', 'flag' => 'pw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palestine, State of ', 'flag' => 'ps ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Panama ', 'flag' => 'pa ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Papua New Guinea ', 'flag' => 'pg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Paraguay ', 'flag' => 'py ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Peru ', 'flag' => 'pe ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Philippines ', 'flag' => 'ph ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pitcairn ', 'flag' => 'pn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Poland ', 'flag' => 'pl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Portugal ', 'flag' => 'pt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Puerto Rico ', 'flag' => 'pr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Qatar ', 'flag' => 'qa ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Republic of North Macedonia ', 'flag' => 'mk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Romania ', 'flag' => 'ro ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Russian Federation ', 'flag' => 'ru ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rwanda ', 'flag' => 'rw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Réunion ', 'flag' => 're ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Barthélemy ', 'flag' => 'bl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha ', 'flag' => 'sh ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Kitts and Nevis ', 'flag' => 'kn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Lucia ', 'flag' => 'lc ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Martin (French part) ', 'flag' => 'mf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Pierre and Miquelon ', 'flag' => 'pm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saint Vincent and the Grenadines ', 'flag' => 'vc ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Samoa ', 'flag' => 'ws ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Marino ', 'flag' => 'sm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sao Tome and Principe ', 'flag' => 'st ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saudi Arabia ', 'flag' => 'sa ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Senegal ', 'flag' => 'sn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Serbia ', 'flag' => 'rs ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Seychelles ', 'flag' => 'sc ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sierra Leone ', 'flag' => 'sl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Singapore ', 'flag' => 'sg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sint Maarten (Dutch part) ', 'flag' => 'sx ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Slovakia ', 'flag' => 'sk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Slovenia ', 'flag' => 'si ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Solomon Islands ', 'flag' => 'sb ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Somalia ', 'flag' => 'so ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'South Africa ', 'flag' => 'za ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'South Georgia and the South Sandwich Islands ', 'flag' => 'gs ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'South Sudan ', 'flag' => 'ss ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Spain ', 'flag' => 'es ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sri Lanka ', 'flag' => 'lk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sudan ', 'flag' => 'sd ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Suriname ', 'flag' => 'sr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Svalbard and Jan Mayen ', 'flag' => 'sj ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sweden ', 'flag' => 'se ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Switzerland ', 'flag' => 'ch ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Syrian Arab Republic ', 'flag' => 'sy ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Taiwan (Province of China) ', 'flag' => 'tw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tajikistan ', 'flag' => 'tj ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tanzania, United Republic of ', 'flag' => 'tz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Thailand ', 'flag' => 'th ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Timor-Leste ', 'flag' => 'tl ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Togo ', 'flag' => 'tg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tokelau ', 'flag' => 'tk ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tonga ', 'flag' => 'to ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Trinidad and Tobago ', 'flag' => 'tt ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tunisia ', 'flag' => 'tn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Turkey ', 'flag' => 'tr ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Turkmenistan ', 'flag' => 'tm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Turks and Caicos Islands ', 'flag' => 'tc ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tuvalu ', 'flag' => 'tv ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Uganda ', 'flag' => 'ug ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ukraine ', 'flag' => 'ua ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'United Arab Emirates ', 'flag' => 'ae ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'United Kingdom of Great Britain and Northern Ireland ', 'flag' => 'gb ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'United States Minor Outlying Islands ', 'flag' => 'um ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'United States of America ', 'flag' => 'us ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Uruguay ', 'flag' => 'uy ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Uzbekistan ', 'flag' => 'uz ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Vanuatu ', 'flag' => 'vu ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Venezuela (Bolivarian Republic of) ', 'flag' => 've ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Viet Nam ', 'flag' => 'vn ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Virgin Islands (British) ', 'flag' => 'vg ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Virgin Islands (U.S.) ', 'flag' => 'vi ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Wallis and Futuna ', 'flag' => 'wf ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Western Sahara ', 'flag' => 'eh ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Yemen ', 'flag' => 'ye ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Zambia ', 'flag' => 'zm ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Zimbabwe ', 'flag' => 'zw ', 'status' => 1,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];

        DB::table('nationalities')->insert($nationalities);
    }
}
